version: '3.7'

services:
  s3-backup-restore:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      AWS_REGION: us-west-2
      DATA_DIRECTORY: /data
      S3_BUCKET: s3-backup-restore-dev-test
      ENABLE_CRON: "true"
    volumes:
      - ./test-data:/data
      - ./:/app
      - ./tmp:/tmp
      - ./docker/dev-secrets/.aws:/root/.aws
    tty: true
    command:
      - go
      - run
      - main.go
