version: '3.7'

services:
  python:
    build:
      context: .
      dockerfile: deploy/docker/python/Dockerfile
    environment:
      AWS_REGION: us-west-2
      DATA_DIRECTORY: /data
      S3_PATH: s3://demon-backup/test-backup
    volumes:
      - ./s3-backup-restore/entrypoint.sh:/root/entrypoint.sh
      - ./s3-backup-restore/run.sh:/root/run.sh
      - ./test-data:/data
    secrets:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY

secrets:
  AWS_ACCESS_KEY:
    file: ./deploy/docker/dev-secrets/AWS_ACCESS_KEY
  AWS_SECRET_KEY:
    file: ./deploy/docker/dev-secrets/AWS_SECRET_KEY
