version: '3.7'

services:
  s3-backup-restore:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: builder
    environment:
      AWS_REGION: us-west-2
      DATA_DIRECTORY: /data
      S3_BUCKET: s3-backup-restore-dev-test
    volumes:
      - ./test-data:/data
      - ./:/app
      - ./docker/dev-secrets/.aws:/root/.aws
    tty: true
    command:
      - go
      - run
      - cmd/s3-backup-restore/main.go
      - -v
      - restore
