version: '3.7'

services:
  s3-backup-restore:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      AWS_REGION: us-west-2
      DATA_DIRECTORY: /data
      S3_PATH: s3://demon-backup/test-backup
    volumes:
      - ./test-data:/data
      - ./:/app
      - ./tmp:/tmp
    secrets:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
    command:
      - go
      - run
      - main.go

secrets:
  AWS_ACCESS_KEY:
    file: ./docker/dev-secrets/AWS_ACCESS_KEY
  AWS_SECRET_KEY:
    file: ./docker/dev-secrets/AWS_SECRET_KEY
